# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - WebAppTestVevo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fdc5c592905645dfa610c423613a7ede }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6094c4ee0c54401eae33e14adb8e1422 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_fdc5c592905645dfa610c423613a7ede }}/tiszolczijacint/azurewebapptest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'WebAppTestVevo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_efc50cf8eaeb4b099a1363252829edea }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_fdc5c592905645dfa610c423613a7ede }}/tiszolczijacint/azurewebapptest:${{ github.sha }}'